// <auto-generated/>
using System.Windows;

namespace GUIConverter
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {
    }
}
